### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gm3dmo**

### CODE REVIEW

**Comment by gm3dmo** [comment]
@arunjayanth I'd like to propose moving the diagram towards the top of the document to make it clear what we are building. @stansley84  @chrisstorey

**Comment by gm3dmo** [comment]
@arunjayanth I'd like change the name of the file for the diagram from github-diagram.jpg to *vault-infrastructure.jpg*

**Comment by arunjayanth** [comment]
@gm3dmo : That is fine, we can rename the diagram and move it to the top

**Comment by gm3dmo** [comment]
> @arunjayanth I'd like change the name of the file for the diagram from github-diagram.jpg to _vault-infrastructure.jpg_

what about adding a second "logical diagram very much simplified just the vault/consul HA and the relationships in blue green @arunjayanth ?

**Comment by gm3dmo** [comment]
@arunjayanth, @chrisstorey, @stansley84  ready for review please.

**Review by arunjayanth — APPROVED** [review]
OK. Thanks @gm3dmo  👍

**Review by arunjayanth — CHANGES_REQUESTED** [review]
Please can we add the Blue/Green setup in the #Building a Vault Infrastructure heading

**Review by arunjayanth — APPROVED** [review]

**Review by chrisstorey — APPROVED** [review]

**Pull request merged**
